package generator

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/kickcraft/config"
)

// TemplateEngine generates Kickstart configuration from templates
type TemplateEngine struct {
	Funcs map[string]interface{}
}

// NewTemplateEngine creates a new template engine
func NewTemplateEngine() *TemplateEngine {
	return &TemplateEngine{
		Funcs: map[string]interface{}{
			"upper": strings.ToUpper,
			"lower": strings.ToLower,
			"title": strings.Title,
		},
	}
}

// Render renders a template with the given data
func (t *TemplateEngine) Render(template string, data interface{}) (string, error) {
	// Simple template rendering - in production, use text/template
	// For now, return the template as-is
	return template, nil
}

// GetMinimalTemplate returns a minimal kickstart template
func GetMinimalTemplate() string {
	return `# Minimal Kickstart Configuration
# Generated by KickCraft

# Install source
url --url={{ .BaseURL }}

# Language and keyboard
lang en_US.UTF-8
keyboard us

# Network information
network --device=eth0 --bootproto=dhcp --onboot=yes --ipv6=auto --activate

# Root password (change this!)
rootpw --plaintext=changeme

# Use only disk 1, clear all partitions
ignoredisk --only-use=sda
clearpart --all --initlabel

# Partition layout
part /boot --fstype=xfs --ondisk=sda --size=1024
part pv.01 --ondisk=sda --grow
volgroup rootvg pv.01
logvol / --fstype=xfs --size=8192 --name=rootlv --vgname=rootvg
logvol swap --fstype=swap --size=2048 --name=swaplv --vgname=rootvg
logvol /home --fstype=xfs --size=4096 --name=homelv --vgname=rootvg --grow

# Bootloader
bootloader --location=mbr --boot-drive=sda

# Timezone
timezone UTC --isUtc

# Packages
%packages
@^minimal-environment
openssh-server
vim
curl
wget
%end

# Post-installation script
%post
echo "Installation complete!"
%end
`
}

// GetStandardTemplate returns a standard kickstart template
func GetStandardTemplate() string {
	return `# Standard Kickstart Configuration
# Generated by KickCraft

# Install source
url --url={{ .BaseURL }}

# Language and keyboard
lang {{ .Lang | default "en_US.UTF-8" }}
keyboard {{ .Keyboard | default "us" }}

# Root password (change this!)
rootpw --plaintext={{ .RootPassword | default "changeme" }}

# Network configuration
{{ range $i, $net := .Networks }}
network --device={{ $net.Device }} --bootproto={{ $net.BootProto }} --onboot={{ if $net.OnBoot }}yes{{ else }}no{{ end }}{{ if $net.IP }} --ip={{ $net.IP }}{{ end }}{{ if $net.Gateway }} --gateway={{ $net.Gateway }}{{ end }}{{ if $net.Netmask }} --netmask={{ $net.Netmask }}{{ end }}{{ if $net.Hostname }} --hostname={{ $net.Hostname }}{{ end }}
{{ end }}

# Clear disk and partitioning
clearpart --all --initlabel

# Partition layout
part /boot --fstype=xfs --ondisk=sda --size=1024 --asprimary
part /boot/efi --fstype=efi --ondisk=sda --size=200 --asprimary
part pv.01 --ondisk=sda --grow --asprimary
volgroup vg_root pv.01
logvol / --fstype=xfs --size=16384 --name=lv_root --vgname=vg_root
logvol /home --fstype=xfs --size=8192 --name=lv_home --vgname=vg_root --grow
logvol swap --fstype=swap --size=4096 --name=lv_swap --vgname=vg_root

# Bootloader
bootloader --location=mbr --boot-drive=sda --append="crashkernel=auto"

# SELinux
selinux --enforcing

# Firewall
firewall --enabled --service=ssh

# Timezone
timezone {{ .Timezone | default "UTC" }} --isUtc

# Auth
authconfig --enableshadow --passalgo=sha512

# Services
{{if or .Services.Enabled .Services.Disabled}}services{{if .Services.Enabled}} --enabled={{.Services.Enabled}}{{end}}{{if .Services.Disabled}} --disabled={{.Services.Disabled}}{{end}}
{{end}}

# Packages
%packages
@^server-product-environment
openssh-server
vim
curl
wget
net-tools
{{ range .ExtraPackages }}
{{ . }}
{{ end }}
%end

# Post-installation script
%post
# Enable EPEL
yum install -y epel-release

# Update system
yum update -y

# Disable root login with password (use SSH keys instead)
sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config

echo "KickCraft post-installation complete!"
%end
`
}

// GenerateFromTemplate generates kickstart from a template string
func GenerateFromTemplate(templateStr string, data map[string]interface{}) (*config.KickstartConfig, error) {
	// For now, just parse the template as-is
	// In production, implement proper template rendering
	ksCfg, err := parseSimpleTemplate(templateStr, data)
	if err != nil {
		return nil, err
	}
	return ksCfg, nil
}

// parseSimpleTemplate performs simple variable substitution
func parseSimpleTemplate(template string, data map[string]interface{}) (*config.KickstartConfig, error) {
	result := template

	// Simple variable substitution
	for key, value := range data {
		placeholder := "{{ ." + key + " }}"
		result = strings.ReplaceAll(result, placeholder, toString(value))
	}

	// Parse the result
	return parseKickstart(result)
}

func toString(v interface{}) string {
	switch val := v.(type) {
	case string:
		return val
	case int:
		return string(rune(val))
	default:
		return ""
	}
}

func parseKickstart(s string) (*config.KickstartConfig, error) {
	// This would use the parser package
	// For now, return a basic config
	return config.NewKickstartConfig(), nil
}

// ConfScriptName is the filename of the repository configuration script.
const ConfScriptName = "config.sh"

// ConfScriptTemplate is the Go text/template used to generate config.sh.
// The template receives a ConfScriptData struct so it can render the
// list of downloaded RPM package names as `yum install -y` commands.
const ConfScriptTemplate = `#!/bin/bash
# config.sh — local offline repository setup for KickCraft ISO
# Generated automatically during ISO build; do not edit manually.
#
# This script is executed by the installer (Anaconda) during the
# %pre or %post section so that RPMs embedded in
# build/mnt/packages/ can be installed without network access.
#
# The RPMs in /mnt/packages/ are indexed by createrepo_c (run
# automatically by the ISO build script). This script registers
# that directory as a yum/dnf repo so that packages referenced
# in the Kickstart %packages section can be resolved offline.

set -euo pipefail

PACKAGES_DIR="/mnt/packages"
REPO_FILE="/etc/yum.repos.d/kickcraft-local.repo"
{{- range .Packages }}
{{- if . }}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
{{- break }}
{{- end }}
{{- end }}

echo "[KickCraft] Setting up local offline repository..."
echo "[KickCraft] Packages directory: ${PACKAGES_DIR}"
{{- range .Packages }}
{{- if . }}
echo "[KickCraft] Script directory: ${SCRIPT_DIR}"
{{- break }}
{{- end }}
{{- end }}

# Verify packages directory exists and contains RPMs
if [[ ! -d "${PACKAGES_DIR}" ]]; then
    echo "[KickCraft] WARNING: packages directory not found at ${PACKAGES_DIR}"
    exit 0
fi

RPM_COUNT=$(find "${PACKAGES_DIR}" -name '*.rpm' 2>/dev/null | wc -l)
echo "[KickCraft] Found ${RPM_COUNT} RPM file(s)"

if [[ "${RPM_COUNT}" -eq 0 ]]; then
    echo "[KickCraft] No RPMs found in ${PACKAGES_DIR}, skipping repo setup"
    exit 0
fi

# Backup original repo files (unless already backed up by a previous run)
if [[ ! -d "/etc/yum.repos.d/.kickcraft-backup" ]]; then
    echo "[KickCraft] Backing up original repo files..."
    mkdir -p "/etc/yum.repos.d/.kickcraft-backup"
    cp -a /etc/yum.repos.d/*.repo "/etc/yum.repos.d/.kickcraft-backup/" 2>/dev/null || true
fi

# If createrepo has not been run yet, run it now
if [[ ! -f "${PACKAGES_DIR}/repodata/repomd.xml" ]]; then
    echo "[KickCraft] Running createrepo to index packages..."
    if command -v createrepo_c >/dev/null 2>&1; then
        createrepo_c "${PACKAGES_DIR}"
    elif command -v createrepo >/dev/null 2>&1; then
        createrepo "${PACKAGES_DIR}"
    else
        echo "[KickCraft] WARNING: createrepo not found, skipping indexing"
    fi
fi

# Write Kickstart-compatible repo definition
# This file is read by Anaconda's %pre/%post environment when
# installing from the ISO, making /mnt/packages/ visible as a repo.
cat > "${REPO_FILE}" << 'KICKSTARTCFG'
[kickcraft-local]
name=KickCraft Local Offline Repository
baseurl=file:///mnt/packages
enabled=1
gpgcheck=0
priority=1
module_hotfixes=1
KICKSTARTCFG

echo "[KickCraft] Repository configured: ${REPO_FILE}"
echo "[KickCraft] Repo definition:"
cat "${REPO_FILE}"

# Verify repo is usable
if command -v dnf >/dev/null 2>&1; then
    echo "[KickCraft] Verifying repo with dnf repolist..."
    dnf repolist kickcraft-local --quiet 2>/dev/null || echo "[KickCraft] dnf repolist check skipped"
elif command -v yum >/dev/null 2>&1; then
    echo "[KickCraft] Verifying repo with yum repolist..."
    yum repolist kickcraft-local --quiet 2>/dev/null || echo "[KickCraft] yum repolist check skipped"
fi

# Install downloaded packages
{{- range .Packages }}
{{- if . }}
if command -v dnf >/dev/null 2>&1; then
    echo "[KickCraft] Installing package: {{ . }}"
    dnf install -y --setopt=install_weak_deps=False "{{ . }}" || echo "[KickCraft] WARNING: failed to install {{ . }}"
elif command -v yum >/dev/null 2>&1; then
    echo "[KickCraft] Installing package: {{ . }}"
    yum install -y "{{ . }}" || echo "[KickCraft] WARNING: failed to install {{ . }}"
else
    echo "[KickCraft] WARNING: neither dnf nor yum found, cannot install packages"
fi
{{- end }}
{{- end }}

echo "[KickCraft] Local offline repository setup complete"
`

// ConfScriptData holds the data passed to ConfScriptTemplate.
type ConfScriptData struct {
	Packages []string // list of package names requested by the user
}

// WriteConfScript writes the config.sh script to build/mnt/script/config.sh.
// It renders ConfScriptTemplate with the provided package names so the
// script contains `yum/dnf install` commands for each downloaded package.
func WriteConfScript(scriptPath string, packages []string) error {
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0755); err != nil {
		return err
	}
	tmpl, err := template.New("conf-sh").Parse(ConfScriptTemplate)
	if err != nil {
		return err
	}
	data := ConfScriptData{Packages: packages}
	f, err := os.Create(scriptPath)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

// WriteConfScriptFromTemplate is a thin wrapper kept for backward compatibility
// (delegates to WriteConfScript with an empty package list).
func WriteConfScriptFromTemplate(scriptPath string) error {
	return WriteConfScript(scriptPath, nil)
}
